### ISSUE TITLE
Automated snapshots can fill up the disk

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/timeshift#13]
Resulting in the inability to log in graphically.

Original bug report: https://github.com/teejee2008/timeshift/issues/332

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/timeshift/commit/22b0e16a265a0debf2227390520ada1954e3f093

**Comment by christophra** [comment]
This fix should be part of 22.06.5, right? In my case that's only one half of the solution, since Timeshift still happily fills up the partition while believing it has 34.7 GB  available space. (Confirmed by "no space left on device" errors.) 

If you have tips for troubleshooting this, I'd appreciate them. But from my point of view, the short story is that the bug persists, and so I'm very sorry but the issue might need to be re-opened.
