### ISSUE TITLE
Seemingly random crash while creating or deleting snapshot.

### ISSUE THREAD

**Issue by fredcw** [linuxmint/timeshift#69]
**System:**
 - Linux Distribution: Manjaro cinnamon
 - timeshift version 22.06.5, libc 2.36

Timeshift crashed twice while creating snapshot at seemingly random moment and also once while deleting snapshot. On the 3rd attempt to create snapshot, it worked normally.

Terminal output while creating snapshot:
```
App config loaded: /etc/timeshift/timeshift.json
Mounted '/dev/sda2' at '/run/timeshift/2706/backup'

------------------------------------------------------------------------------
Creating new snapshot...(RSYNC)
Saving to device: /dev/sda2, mounted at path: /run/timeshift/2706/backup
Linking from snapshot: 2022-09-14_08-46-23
Syncing files with rsync...
**7.36% complete (00:00:19 remaining)
ERROR:/build/timeshift/src/timeshift/src/Utility/TeeJee.Misc.vala.c:516:string_replace: code should not be reached
Bail out! ERROR:/build/timeshift/src/timeshift/src/Utility/TeeJee.Misc.vala.c:516:string_replace: code should not be reached
/usr/bin/timeshift-launcher: line 30:  2706 Aborted                 (core dumped) pkexec ${app_command}
```
journalctl:

```
Oct 01 03:57:35 fred-manjaro-cinnamon systemd[1]: Started Process Core Dump (PID 3023/UID 0).
Oct 01 03:57:35 fred-manjaro-cinnamon systemd-coredump[3024]: [🡕] Process 2706 (timeshift-gtk) of user 0 dumped core.
                                                              
                                                              Module linux-vdso.so.1 with build-id 6a6aaf8fbb636bd2ab94dd5d8b44be5f8d4a6eb7
                                                              Module librsvg-2.so.2 with build-id c5d3f3e2ba0718c84f4f6f02974929f5459dde04
                                                              Module libpixbufloader-svg.so with build-id a145d079b95f06b08de3a1916110250de1ee889e
                                                              Module libnss_systemd.so.2 with build-id b7482bac90954fa3309c422c158d46c7ea27464b
                                                              Module libxkbfile.so.1 with build-id dc74ddc73cb1178f037cdc608f7029a0bc9f69a1
                                                              Module libgpg-error.so.0 with build-id 4738b8a9478177c202cccd64e0eb65d3dea2bfae
                                                              Module libbrotlicommon.so.1 with build-id acfd597a977c8087bb6184383daae2e828a9ce42
                                                              Module libpthread.so.0 with build-id 3954d7fd57fa4db438d0ccdd8e2c6f7cc97c2e46
                                                              Module libdl.so.2 with build-id 414d1d630bc04818a150b9c73e4493f3395e8869
                                                              Module libblkid.so.1 with build-id fb2c5d3c17aac74758a3eb80a2bc1c16bcf183b1
                                                              Module libbz2.so.1.0 with build-id 919597c477c9b2cb9cdbb7745ed6494ac0e6da60
                                                              Module libdatrie.so.1 with build-id 6fe3b6ece2c8e7d11869fa051375128d8f808f58
                                                              Module libsqlite3.so.0 with build-id 9af0762dc0b9aa82565f566ef69424a8e4af58da
                                                              Module libxml2.so.2 with build-id 49868de417eee9052facae410a866ebfbd5cceb8
                                                              Module libicui18n.so.71 with build-id 6fd5c97fd2808ee29958bf809656d5885e7e8963
                                                              Module libstemmer.so.0 with build-id 013b48e71279a5ec55e3021fc0bd8fb10a08bae5
                                                              Module libdbus-1.so.3 with build-id 130b4008893289a2628546d8f98f6977d61270cd
                                                              Module libatspi.so.0 with build-id 51fdaad17db96c5569b8f59908e7c076fbd6fe1c
                                                              Module libexpat.so.1 with build-id 52f685635e8711c1164d20a1ef8acd3840312094
                                                              Module libxklavier.so.16 with build-id cefd678b3d270e389f50a9686ad2db83a8c67494
                                                              Module libgnomekbd.so.8 with build-id 9b50613358fc5812925d41109dae2ae6037d4310
                                                              Module liblz4.so.1 with build-id 84ea95d811dad359e94e100ebe6a746294ffe8a7
                                                              Module liblzma.so.5 with build-id d08f5868cd5adcc6b7c53bf1725aac65bd4539cd
                                                              Module libgcrypt.so.20 with build-id 8bf3cb884124273640de797a3e77d86c98434ea4
                                                              Module libcap.so.2 with build-id 9b38b08de708f439a9d0a4f8b9914151bc8d4b50
                                                              Module libicudata.so.71 with build-id 4fef196388e678deb881978139e125e20ee2d94d
                                                              Module libgmp.so.10 with build-id 26cec2ebe94cc5c4cb99e6988717347222b324fd
                                                              Module libhogweed.so.6 with build-id 5c4a99ad0aabe13bd9b517f92ab339436a2bc1f2
                                                              Module libnettle.so.8 with build-id 6a26cbe6819abc8c57668f80ca8c8160fd85e29e
                                                              Module libtasn1.so.6 with build-id fa2f7a5bfbcda1481ab5875d5744730ea1be8fb1
                                                              Module libunistring.so.2 with build-id 617dbf3d3d6f85d6556a7a036e23845e95490158
                                                              Module libidn2.so.0 with build-id b16e7570b102789b13ff77289762dbfe3f8f46bc
                                                              Module libzstd.so.1 with build-id ab54c2881f53ab314e134f3e08c76d504376dd5d
                                                              Module libbrotlidec.so.1 with build-id 66c54e9301f7e102ecc1d88547e5f0e8a056fe22
                                                              Module libbrotlienc.so.1 with build-id 74adbc62e4fbb5da9d37b5aa458471f4130862ff
                                                              Module libp11-kit.so.0 with build-id cc372ea3c28c4d3dfc633b4d2e933c8584d2af16
                                                              Module libXdmcp.so.6 with build-id d864159ab0008415667db8d5f251696d75c90df2
                                                              Module libXau.so.6 with build-id d9d5e8277140f1a86d3a07d9b52b1703c0a2f9a8
                                                              Module ld-linux-x86-64.so.2 with build-id 075a6ad9f1c3f9cbb5f3301186bbe68c6a477808
                                                              Module libpixman-1.so.0 with build-id d2170a3ac106c2a68597bf7910ab04b1cdd69c14
                                                              Module libxcb-shm.so.0 with build-id 828fec4d856e2710e732ea8d92c3f250c807b1c2
                                                              Module libxcb-render.so.0 with build-id b1ca498d665807ab0ccdafbe8070853efd058173
                                                              Module libXrender.so.1 with build-id 42e386d2acf3cde61081959d9671ca74acfb3edc
                                                              Module libffi.so.8 with build-id fb5dba105458f179a9153659f3ccd8e1056a2f35
                                                              Module libmount.so.1 with build-id 9064fc3620c42e6f7aed38119f0a3ec39fca9a37
                                                              Module libtiff.so.5 with build-id 62a8aefb339c3cbe35d1089c66c527a7b090804c
                                                              Module libjpeg.so.8 with build-id 46dfd8b2cbe8a10d13cd3182a7b490d0959534f9
                                                              Module libpng16.so.16 with build-id 14d3b3cc9d61ec1b7c1f86bdf108218a99364945
                                                              Module libgraphite2.so.3 with build-id ce58945ebb55b86d3a4e717b6eae29efc4720d8e
                                                              Module libfreetype.so.6 with build-id f89dd5502e75aca28fb5c3ccd0dbd26fe822bfef
                                                              Module libthai.so.0 with build-id a7ac5010b4275c49308021200d23690533952702
                                                              Module libXinerama.so.1 with build-id 8198240259261b612189e89c9fcfc902b025b382
                                                              Module libXrandr.so.2 with build-id 154e55f082ee9e685d0794c98c5b76ffe9c8868e
                                                              Module libXcomposite.so.1 with build-id 13228d108b290268d88510db494daefd5521cda0
                                                              Module libXdamage.so.1 with build-id a99dbe3fc2b01da9fbdd90d5ad00621f9022379f
                                                              Module libXcursor.so.1 with build-id f0525ae3715ac95f96a8cdb44795b03f831334b0
                                                              Module libXext.so.6 with build-id 17beadf1cb40d41ab36629db3b4eed74110678a7
                                                              Module libwayland-egl.so.1 with build-id dd02a2af320297e68308cc698f75828529271a57
                                                              Module libwayland-cursor.so.0 with build-id 46a637dbcbb02d6712a201f177377b66598b9121
                                                              Module libwayland-client.so.0 with build-id 515c72111400d7bdbfbdfcec78d597e4986a5943
                                                              Module libxkbcommon.so.0 with build-id 6cf66eead3fcc20fe5df10162bfbcdcdc8b2a183
                                                              Module libXfixes.so.3 with build-id 0a05c7e8714522bfbdd7c0027c3e2a94965664b0
                                                              Module libtracker-sparql-3.0.so.0 with build-id b4ae6341a6b845e55701dd4577a12cdc3ec0c73e
                                                              Module libcloudproviders.so.0 with build-id ed1d9c9e60be4e858ad148484767249be1edf95f
                                                              Module libatk-bridge-2.0.so.0 with build-id 75ddfc46abae129a83449506506501117ce98ff8
                                                              Module libXi.so.6 with build-id 16603be937a02a7e61b0b0395d064be7efd86f49
                                                              Module libepoxy.so.0 with build-id edc178a150c4255d124e1e1ecbdbecebd1a388cd
                                                              Module libfontconfig.so.1 with build-id 36be6951b8c1e42a7dd05684a37400fc8ef9147c
                                                              Module libpangoft2-1.0.so.0 with build-id 007c5a54e838e649215b740df9568e4d4c9c6507
                                                              Module libgnomekbdui.so.8 with build-id 8587f7b950d379edef6c112b68075b3388b43b86
                                                              Module libgcc_s.so.1 with build-id 85db482c4585a328d95ec41124337a967bb24d8f
                                                              Module libstdc++.so.6 with build-id 735a3d0cc7699fd69337361cba4aedb644b2a7ed
                                                              Module libsystemd.so.0 with build-id f53e01cd7b3e5ff8757530ed7a65324ae12df5c8
                                                              Module libicuuc.so.71 with build-id 633fdc0c5385d916571f6140e7a978ad0630ef55
                                                              Module libgnutls.so.30 with build-id e849ad24d363553f5ddc88d43926e1ab2601ada9
                                                              Module libfribidi.so.0 with build-id fe9f35ac2a0074108c8306c517793f7279bd9b37
                                                              Module libxcb.so.1 with build-id 13d677412a71468381b11092915d231f664d18d3
                                                              Module libpcre2-8.so.0 with build-id 917fc43d2c9f8539a3e324555c6c73886e8000a8
                                                              Module libc.so.6 with build-id 90b9e4f641f8752292698389f241cbf0ff49d687
                                                              Module libm.so.6 with build-id 2c8ff1d29b255da5b7371efd5caf57444d622838
                                                              Module libcairo.so.2 with build-id a222d042e56108d2786ece7bf291b56ba2069591
                                                              Module libgobject-2.0.so.0 with build-id afb0315fefdf602be0615bd5c97f35a7ac1d6bbe
                                                              Module libgio-2.0.so.0 with build-id 804d947f8cb14bbbbf97e8bf2f93fd17b744e719
                                                              Module libgdk_pixbuf-2.0.so.0 with build-id b2822dc16bd1470683ce421978ad142c4f3c3f89
                                                              Module libcairo-gobject.so.2 with build-id 9927090dddfb180365695a8f37d1cac89463f109
                                                              Module libatk-1.0.so.0 with build-id c25517cd775e783725a3ed2815b09a8096bd6565
                                                              Module libharfbuzz.so.0 with build-id 0083e085bcb9cb3869e5cb05fbcd9736c41434ab
                                                              Module libpango-1.0.so.0 with build-id bdcd807766c7b943b1ba1a00343adf73799e3f83
                                                              Module libpangocairo-1.0.so.0 with build-id 68bcb6fe10c46cb09c7228206e4dbb7e3940fd34
                                                              Module libz.so.1 with build-id fefe3219a96d682ec98fcfb78866b8594298b5a2
                                                              Module libgdk-3.so.0 with build-id f3bc07ea30b1a84c4e3df1d67deaadfcf747bc3c
                                                              Module libgtk-3.so.0 with build-id f25162b866dd8b576794f6f06b91a36ac8f570f8
                                                              Module libxapp.so.1 with build-id af7ce569cda64b23f0b4eea7018c0766b346ec38
                                                              Module libvte-2.91.so.0 with build-id 360ab033f3d0130660da4752207cb7a6923c535f
                                                              Module libX11.so.6 with build-id 21e886e968772b7964d646f54c1faecc56734de9
                                                              Module libharfbuzz-gobject.so.0 with build-id 635f6578ccaa6d420c29806823569807388dfa34
                                                              Module libglib-2.0.so.0 with build-id 3ef8f9239c93af698703b12c5c6738fe0129eaa7
                                                              Module libgmodule-2.0.so.0 with build-id 95ec7a190858206b2eaba22e06b126e4a4449200
                                                              Module libjson-glib-1.0.so.0 with build-id 58decebd2c409d59b07f926ae4c513281918bc4d
                                                              Module libgee-0.8.so.2 with build-id 5cdccd3d1b5d1cc3e9ff84eaa95b3898aeaf7857
                                                              Module timeshift-gtk with build-id 05039dd659565d6a5c27543de09e9c5c523e4351
                                                              Stack trace of thread 2706:
                                                              #0  0x00007f2f93ba949c n/a (libc.so.6 + 0x8849c)
                                                              #1  0x00007f2f93b59958 raise (libc.so.6 + 0x38958)
                                                              #2  0x00007f2f93b4353d abort (libc.so.6 + 0x2253d)
                                                              #3  0x00007f2f94e3606a n/a (libglib-2.0.so.0 + 0x1d06a)
                                                              #4  0x00007f2f94e918d0 g_assertion_message_expr (libglib-2.0.so.0 + 0x788d0)
                                                              #5  0x0000565494e864bb n/a (timeshift-gtk + 0xfb4bb)
                                                              #6  0x0000565494e8657d tee_jee_misc_escape_html (timeshift-gtk + 0xfb57d)
                                                              #7  0x0000565494deba94 backup_box_take_snapshot (timeshift-gtk + 0x60a94)
                                                              #8  0x0000565494df6a5a n/a (timeshift-gtk + 0x6ba5a)
                                                              #9  0x0000565494df6284 n/a (timeshift-gtk + 0x6b284)
                                                              #10 0x0000565494df58a2 n/a (timeshift-gtk + 0x6a8a2)
                                                              #11 0x0000565494df4ed1 n/a (timeshift-gtk + 0x69ed1)
                                                              #12 0x00007f2f94e6f042 n/a (libglib-2.0.so.0 + 0x56042)
                                                              #13 0x00007f2f94e6e81b g_main_context_dispatch (libglib-2.0.so.0 + 0x5581b)
                                                              #14 0x00007f2f94ec4ec9 n/a (libglib-2.0.so.0 + 0xabec9)
                                                              #15 0x00007f2f94e6dd7f g_main_loop_run (libglib-2.0.so.0 + 0x54d7f)
                                                              #16 0x00007f2f9460fe9f gtk_main (libgtk-3.so.0 + 0x1d8e9f)
                                                              #17 0x0000565494de9c62 app_gtk_start_application (timeshift-gtk + 0x5ec62)
                                                              #18 0x0000565494de90d8 n/a (timeshift-gtk + 0x5e0d8)
                                                              #19 0x0000565494de9120 main (timeshift-gtk + 0x5e120)
                                                              #20 0x00007f2f93b44290 n/a (libc.so.6 + 0x23290)
                                                              #21 0x00007f2f93b4434a __libc_start_main (libc.so.6 + 0x2334a)
                                                              #22 0x0000565494da3245 _start (timeshift-gtk + 0x18245)
                                                              
                                                              Stack trace of thread 2758:
                                                              #0  0x00007f2f93c1be5f __poll (libc.so.6 + 0xfae5f)
                                                              #1  0x00007f2f94ec4e2f n/a (libglib-2.0.so.0 + 0xabe2f)
                                                              #2  0x00007f2f94e6d0d2 g_main_context_iteration (libglib-2.0.so.0 + 0x540d2)
                                                              #3  0x00007f2f94e6d122 n/a (libglib-2.0.so.0 + 0x54122)
                                                              #4  0x00007f2f94e9bc55 n/a (libglib-2.0.so.0 + 0x82c55)
                                                              #5  0x00007f2f93ba774d n/a (libc.so.6 + 0x8674d)
                                                              #6  0x00007f2f93c29700 n/a (libc.so.6 + 0x108700)
                                                              
                                                              Stack trace of thread 2827:
                                                              #0  0x00007f2f93c1be5f __poll (libc.so.6 + 0xfae5f)
                                                              #1  0x00007f2f94044041 n/a (libgio-2.0.so.0 + 0xce041)
                                                              #2  0x00007f2f93fec635 g_input_stream_read (libgio-2.0.so.0 + 0x76635)
                                                              #3  0x00007f2f93fb71c1 n/a (libgio-2.0.so.0 + 0x411c1)
                                                              #4  0x00007f2f93fb7e34 g_buffered_input_stream_fill (libgio-2.0.so.0 + 0x41e34)
                                                              #5  0x00007f2f93fc0dc7 g_data_input_stream_read_line (libgio-2.0.so.0 + 0x4adc7)
                                                              #6  0x0000565494e40656 n/a (timeshift-gtk + 0xb5656)
                                                              #7  0x0000565494e3f127 n/a (timeshift-gtk + 0xb4127)
                                                              #8  0x00007f2f94e9bc55 n/a (libglib-2.0.so.0 + 0x82c55)
                                                              #9  0x00007f2f93ba774d n/a (libc.so.6 + 0x8674d)
                                                              #10 0x00007f2f93c29700 n/a (libc.so.6 + 0x108700)
                                                              
                                                              Stack trace of thread 2826:
                                                              #0  0x00007f2f93c1be5f __poll (libc.so.6 + 0xfae5f)
                                                              #1  0x00007f2f94044041 n/a (libgio-2.0.so.0 + 0xce041)
                                                              #2  0x00007f2f93fec635 g_input_stream_read (libgio-2.0.so.0 + 0x76635)
                                                              #3  0x00007f2f93fb71c1 n/a (libgio-2.0.so.0 + 0x411c1)
                                                              #4  0x00007f2f93fb7e34 g_buffered_input_stream_fill (libgio-2.0.so.0 + 0x41e34)
                                                              #5  0x00007f2f93fc0dc7 g_data_input_stream_read_line (libgio-2.0.so.0 + 0x4adc7)
                                                              #6  0x0000565494e4023e n/a (timeshift-gtk + 0xb523e)
                                                              #7  0x0000565494e3f0f5 n/a (timeshift-gtk + 0xb40f5)
                                                              #8  0x00007f2f94e9bc55 n/a (libglib-2.0.so.0 + 0x82c55)
                                                              #9  0x00007f2f93ba774d n/a (libc.so.6 + 0x8674d)
                                                              #10 0x00007f2f93c29700 n/a (libc.so.6 + 0x108700)
                                                              
                                                              Stack trace of thread 2813:
                                                              #0  0x00007f2f93bee545 clock_nanosleep (libc.so.6 + 0xcd545)
                                                              #1  0x00007f2f93bf3057 __nanosleep (libc.so.6 + 0xd2057)
                                                              #2  0x00007f2f94e99391 g_usleep (libglib-2.0.so.0 + 0x80391)
                                                              #3  0x0000565494e8ecc4 tee_jee_system_sleep (timeshift-gtk + 0x103cc4)
                                                              #4  0x0000565494db71fb n/a (timeshift-gtk + 0x2c1fb)
                                                              #5  0x0000565494db413c n/a (timeshift-gtk + 0x2913c)
                                                              #6  0x0000565494db119a main_create_snapshot (timeshift-gtk + 0x2619a)
                                                              #7  0x0000565494dec59c n/a (timeshift-gtk + 0x6159c)
                                                              #8  0x0000565494deb46e n/a (timeshift-gtk + 0x6046e)
                                                              #9  0x00007f2f94e9bc55 n/a (libglib-2.0.so.0 + 0x82c55)
                                                              #10 0x00007f2f93ba774d n/a (libc.so.6 + 0x8674d)
                                                              #11 0x00007f2f93c29700 n/a (libc.so.6 + 0x108700)
                                                              ELF object binary architecture: AMD x86-64
```

**Comment by cimarronline** [comment]
Yes, I'm seeing the same thing after updating glib2 to version 2.74. Also reported here: https://github.com/linuxmint/timeshift/issues/66

**Comment by GarySeven** [comment]
I have just noticed the exact same error condition on my Arch linux install as OP.  I run several Linux distros from dedicated ssd's on my desktop.  I'm seeing this Timeshift problem on a vanilla Arch install with Cinnamon DE. Arch kernel 5.19.12-arch1-1.  Timeshift v22.06.5.  Running pacman -Qi glib2  shows version 2.74.0-2.

As a side note, I do NOT see this issue under Linux Mint 20.3 (Timeshift v22.06.5), nor under my Fedora 36 installation (also Cinnamon DE) with Timeshift v21.09.1.

So this appears to be an issue with glib2, but of course the problem is not cropping up with either Mint or Fedora as they are running an older version.  Here's hoping the fine devs at Mint can iron this out.

**Comment by GaryElshaw** [comment]
Same thing here on the Ubuntu Kinetic beta.

**Comment by cimarronline** [comment]
Using Timeshift commands in the terminal still works. Only the GUI is affected.

**Comment by RonLinu** [comment]
Same on Manjaro Xfce, kernel 5.15.72-1LTS.
And indeed it works ok using the command line. It even remove the unfinished snapshot(s) when it crashed previously using the GUI.

**Comment by cimarronline** [comment]
@clefebvre A bunch of people are seeing Timeshift fail for them with Arch-based distros, and it looks like glib2 2.74 is included with Ubuntu Kinetic, which I think is being released on Oct 20. (Someone already reported Timeshift crashing with Kinetic beta above.) So this issue could cause a lot more grief soon.

**Comment by GaryElshaw** [comment]
Restore functionality is also broken on the CL with Ubuntu Kinetic (seg fault).

**Comment by watsonism** [comment]
OS: Arch Linux x86_64
Kernel: 6.0.0.11.realtime1-1-rt
Timeshift version: 22.06.5 (built from source one hour before writing this)
glib2 version: 2.74.0-2
I am getting the same error as OP. I have also tried installing "timeshift" and "timeshift-bin" from the AUR instead of building and installing from source (this repo) and still see the same error re: ". . . timeshift/src/Utility/TeeJee.Misc.vala.c:516:string_replace: code should not be reached."

I will try using the command-line version of timeshift after work and report back here if I can.

**Comment by teejee2008** [comment]
This bug does not affect Linux Mint or distributions based on Ubuntu 22.04. 

It is fixed in the commit [5a78bb7](https://github.com/teejee2008/timeshift/commit/5a78bb71ba6c2b6ede7d3a891a4e1c37d7fb4d71)

**Comment by fredcw** [comment]
>It is fixed in the commit [5a78bb7](https://github.com/teejee2008/timeshift/commit/5a78bb71ba6c2b6ede7d3a891a4e1c37d7fb4d71)

I have tested this fix in Mint's version of Timeshift and it does indeed seem to have fixed the problem.

**Comment by ACR-Jeff** [comment]
Same issue here, Debian Bullseye, I am seeing this crash to black screen while creating or restoring, Happens using both GUI and Terminal commands.

**Comment by ACR-Jeff** [comment]
Some time after my post above timeshift randomly fixed itself this far.

**Comment by fredcw** [comment]
@ACR-Jeff I'm not sure why that is. Maybe the debian apt packager has applied the fix and updated the package. The bugfix that @teejee2008 applied was to the version of timeshift in his repository (which has now been archived), but it hasn't been applied to timeshift in this repository yet. It's also fixed in manjaro so I guess the Arch package maintainer has also applied the fix.

**Comment by GarySeven** [comment]
> @ACR-Jeff I'm not sure why that is. Maybe the debian apt packager has applied the fix and updated the package. The bugfix that @teejee2008 applied was to the version of timeshift in his repository (which has now been archived), but it hasn't been applied to timeshift in this repository yet. It's also fixed in manjaro so I guess the Arch package maintainer has also applied the fix.

Issue still exists in pure Arch.  Note that Timeshift I have installed under Arch is the Mint fork.  Just for laughs guess I will remove the package and reinstall the teejee2008 version.

**Comment by ACR-Jeff** [comment]
> @ACR-Jeff I'm not sure why that is. Maybe the debian apt packager has applied the fix and updated the package. The bugfix that @teejee2008 applied was to the version of timeshift in his repository (which has now been archived), but it hasn't been applied to timeshift in this repository yet. It's also fixed in manjaro so I guess the Arch package maintainer has also applied the fix.

I am not sure why or how it it was fixed, I am guessing Debian pushed a security update through that I over looked, Yet I have found 0 information on any glib2 updates via Debian. As we know Debian is pretty serious about stability, Yet odd that I can not find any information on any security updates for glib2 and my issue has been solved mysteriously?

**Comment by ACR-Jeff** [comment]
> @ACR-Jeff I'm not sure why that is. Maybe the debian apt packager has applied the fix and updated the package. The bugfix that @teejee2008 applied was to the version of timeshift in his repository (which has now been archived), but it hasn't been applied to timeshift in this repository yet. It's also fixed in manjaro so I guess the Arch package maintainer has also applied the fix.

I spoke to soon, It worked for a few days and then randomly started crashing again. Timeshift GUI doesn't crash itself, Yet the system crashes to the Console in a never ending loop. This is at random. Maybe a different issue that I will have to research. Thank you.

**Comment by GaryElshaw** [comment]
I started fresh by uninstalling, sorting out the dependencies, and then building/installing [v22.06.6](https://github.com/teejee2008/timeshift/releases/tag/22.06.6). It's been rock solid since.

**Comment by ACR-Jeff** [comment]
> I started fresh by uninstalling, sorting out the dependencies, and then building/installing [v22.06.6](https://github.com/teejee2008/timeshift/releases/tag/22.06.6). It's been rock solid since.

Thank you, Worked for me so far on Debian Bullseye, I had to purge Timeshift, Then follow the instructions here [installation](https://github.com/linuxmint/timeshift#installation) under section `Or build and install timeshift from the source code:` to install dependencies and build with [v22.06.6](https://github.com/teejee2008/timeshift/releases/tag/22.06.6)

**Comment by ACR-Jeff** [comment]
My issue was actually unrelated to Timeshift, Failing system SSD only showing signs while trying to backup using Timeshift, So that being said Timeshift was helpful once again and saved my butt.

**Comment by mtwebster** [comment]
This should be fixed in git master here now, will get a new release soon.
